import "./globals.css";
import { DM_Sans } from "next/font/google";
import { Nanum_Gothic } from "next/font/google";


export const nanumgothic = Nanum_Gothic({
  subsets: ["latin"],
  weight: ["400"],
});

const dmsans = DM_Sans({
  subsets: ["latin"],
  weight: "1000",
});

export const metadata = {
  title: "MY UNIVERSE",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  },
  viewport: {
    initialScale: 1,
    width: "device-width",
    maximumScale: 1,
    minimumScale: 1,
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={dmsans.className}>
      <body>{children}</body>
    </html>
  );
}
