import "./globals.css";
import { DM_Sans } from "next/font/google";
import { Nanum_Gothic } from "next/font/google"


export const nanumgothic = Nanum_Gothic({
  subsets: ["latin"],
  weight: ["400"]
})

const dmsans = DM_Sans({
  subsets: ["latin"],
  weight: "1000",
});

export const viewport = {
  initialScale: 1,
  width: "device-width",
  maximumScale: 1,
};

export const metadata = {
  title: "MY UNIVERSE",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={dmsans.className}>
      <body>
        <img className="texture" src="/noise.png" alt="background" />
        {children}
      </body>
    </html>
  );
}
